import { AuthProvider } from './Providers'
import './globals.css'

export const metadata = {
  title: 'Task Manager',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="dark:bg-gray-800 dark:text-gray-200">
        <div className='max-w-3xl mx-auto p-4'>
          <div className='mt-8'>

          <AuthProvider>
            {children}
          </AuthProvider>
            
            </div>
        </div>
      </body>
    </html>
  )
}
